#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mock
Version  : 1.2.14
Release  : 20
URL      : https://github.com/rpm-software-management/mock/archive/mock-1.2.14.tar.gz
Source0  : https://github.com/rpm-software-management/mock/archive/mock-1.2.14.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: mock-bin
Requires: mock-python
Requires: mock-data
Requires: mock-doc
BuildRequires : pkgconfig(bash-completion)
BuildRequires : python
BuildRequires : python-dev
BuildRequires : python3
Patch1: 0001-Stateless-conversion.patch
Patch2: 0002-Do-not-reuse-mock-group-as-it-might-be-defined-in-th.patch

%description
These 3 src.rpms are setup to build on almost any rpm-based system.
They have a simple chain of buildrequires:

%package bin
Summary: bin components for the mock package.
Group: Binaries
Requires: mock-data

%description bin
bin components for the mock package.


%package data
Summary: data components for the mock package.
Group: Data

%description data
data components for the mock package.


%package doc
Summary: doc components for the mock package.
Group: Documentation

%description doc
doc components for the mock package.


%package python
Summary: python components for the mock package.
Group: Default

%description python
python components for the mock package.


%prep
%setup -q -n mock-mock-1.2.14
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1494963039
%autogen --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1494963039
rm -rf %{buildroot}
%make_install
## make_install_append content
install -d -m 755 %{buildroot}/usr/share/pam.d
install -d -m 755 %{buildroot}/usr/share/defaults/mock
install -p -D -m 644 etc/mock/logging.ini %{buildroot}/usr/share/defaults/mock/
install -p -D -m 644 etc/pam/mock %{buildroot}/usr/share/pam.d/
rm -rf %{buildroot}/etc
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mock
/usr/bin/mockchain

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/mock
/usr/share/bash-completion/completions/mockchain
/usr/share/defaults/mock/logging.ini
/usr/share/pam.d/mock

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
